server:
  port: 9094

spring:
  application:
    name: students-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9090/eureka/
  instance:
    hostname: localhost
